<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // ── Helper: resolve category_id once by slug ──────────────────────
        $categoryMap = Category::pluck('id', 'slug');

        $products = [

            // ════════════════════════════════════════════════════════════
            //  Web Design & Development  (category slug: web-design-development)
            // ════════════════════════════════════════════════════════════
            [
                'category_slug' => 'web-design-development',
                'name'          => 'Website Design & Development - Service Page',
                'short_name'    => 'Service Page',
                'description'   => 'A fully customised WordPress website with up to 25 pages, mobile-responsive design, and 40 hours of development.',
                'scope_items'   => [
                    'WordPress website',
                    'Customised template design',
                    'Up to 25 standard modules/plugins',
                    'Mobile responsive design',
                    'Up to 25 pages',
                    'Multiple contact forms',
                    'Images provided by client',
                    'Shutterstock images included',
                    'Social media integration',
                    'Google Analytics integration',
                    '40 hours of website development',
                    'Existing online ordering link',
                    'Facebook live chat',
                    'SEO ready',
                    'Website training & documentation',
                ],
                'price_type'      => 'dropdown',
                'price_min'       => 3000.00,
                'price_max'       => 9000.00,
                'price_increment' => 500.00,
                'hourly_rate'     => 90.00,
                'frequency'       => 'Once Off',
                'notes'           => 'Hours change based on total price at $90 + GST per hour.',
                'is_active'       => true,
                'sort_order'      => 1,
            ],
            [
                'category_slug' => 'web-design-development',
                'name'          => 'Website Design & Development - Ecommerce',
                'short_name'    => 'Ecommerce',
                'description'   => 'Full ecommerce website solution built on WordPress.',
                'scope_items'   => [],
                'price_type'    => 'dropdown',
                'price_min'       => 3000.00,
                'price_max'       => 9000.00,
                'price_increment' => 500.00,
                'hourly_rate'   => 90.00,
                'frequency'     => 'Once Off',
                'notes'         => 'Hours change based on total price at $90 + GST per hour.',
                'is_active'     => true,
                'sort_order'    => 2,
            ],
            [
                'category_slug' => 'web-design-development',
                'name'          => 'Website Design & Development - Landing Page',
                'short_name'    => 'Landing Page',
                'description'   => 'Professional single-page landing page design and development.',
                'scope_items'   => [],
                'price_type'  => 'fixed',
                'fixed_price' => 1500.00,
                'hourly_rate' => 90.00,
                'frequency'   => 'Once Off',
                'notes'       => 'Hours change based on total price at $90 + GST per hour.',
                'is_active'   => true,
                'sort_order'  => 3,
            ],

            // ════════════════════════════════════════════════════════════
            //  Logo Design & Branding  (category slug: logo-design-branding)
            // ════════════════════════════════════════════════════════════
            [
                'category_slug' => 'logo-design-branding',
                'name'          => 'Logo Design & Branding / Packaging',
                'short_name'    => 'Branding & Packaging',
                'description'   => 'Premium branding pack including logo, business card, email signature, letterhead, and up to 5 packaging designs.',
                'scope_items'   => [
                    'Premium branding pack',
                    'Logo with variations',
                    'Business card template – single name (printing not included)',
                    'Email signature – single name',
                    'Letterhead',
                    'PowerPoint slide',
                    'Social media page design',
                    'Up to 5 packaging/box designs',
                    'Total 21 hours of graphic design',
                ],
                'price_type'      => 'dropdown',
                'price_min'       => 1600.00,
                'price_max'       => 1920.00,
                'price_increment' => 40.00,
                'frequency'       => 'Once Off',
                'is_active'       => true,
                'sort_order'      => 1,
            ],

            // ════════════════════════════════════════════════════════════
            //  Web Hosting  (category slug: web-hosting)
            // ════════════════════════════════════════════════════════════
            [
                'category_slug' => 'web-hosting',
                'name'          => 'Advanced Web Hosting',
                'short_name'    => 'Advanced Hosting',
                'description'   => 'WP Engine advanced hosting with excellent uptime, WordPress-specific security, daily backups, and real-time threat detection.',
                'scope_items'   => [
                    'Fast cache',
                    '24/7 email support',
                    'Threat detection',
                    'Daily backups',
                    '10GB local storage',
                    '50GB bandwidth',
                ],
                'price_type'  => 'fixed',
                'fixed_price' => 239.00,
                'frequency'   => 'yearly',
                'is_active'   => true,
                'sort_order'  => 1,
            ],
            [
                'category_slug' => 'web-hosting',
                'name'          => 'Premium Web Hosting',
                'short_name'    => 'Premium Hosting',
                'description'   => 'WP Engine premium hosting with excellent uptime, WordPress-specific security, daily backups, and real-time threat detection.',
                'scope_items'   => [
                    'Fast cache',
                    '24/7 email support',
                    'Threat detection',
                    'Daily backups',
                    '10GB local storage',
                    '50GB bandwidth',
                ],
                'price_type'  => 'fixed',
                'fixed_price' => 299.00,
                'frequency'   => 'yearly',
                'is_active'   => true,
                'sort_order'  => 2,
            ],
            [
                'category_slug' => 'web-hosting',
                'name'          => 'Domain Registration',
                'short_name'    => 'Domain',
                'description'   => 'Annual domain name registration.',
                'scope_items'   => [],
                'price_type'    => 'fixed',
                'fixed_price'   => 29.00,
                'frequency'     => 'yearly',
                'is_active'     => true,
                'sort_order'    => 3,
            ],
            [
                'category_slug' => 'web-hosting',
                'name'          => 'Cloudflare DNS Management',
                'short_name'    => 'Cloudflare DNS',
                'description'   => 'Annual Cloudflare DNS management service.',
                'scope_items'   => [],
                'price_type'    => 'fixed',
                'fixed_price'   => 120.00,
                'frequency'     => 'yearly',
                'is_active'     => true,
                'sort_order'    => 4,
            ],
            [
                'category_slug' => 'web-hosting',
                'name'          => 'DNS Forwarding',
                'short_name'    => 'DNS Forwarding',
                'description'   => 'Annual DNS forwarding service.',
                'scope_items'   => [],
                'price_type'    => 'fixed',
                'fixed_price'   => 99.00,
                'frequency'     => 'yearly',
                'is_active'     => true,
                'sort_order'    => 5,
            ],

            // ════════════════════════════════════════════════════════════
            //  Managed IT  (category slug: managed-it)
            // ════════════════════════════════════════════════════════════
            [
                'category_slug' => 'managed-it',
                'name'          => 'IT Managed Services - Basic Plan (2 Hrs/Month)',
                'short_name'    => 'IT Basic Plan',
                'description'   => 'Managed IT support – 2 hours of dedicated support per month.',
                'scope_items'   => [],
                'price_type'    => 'fixed',
                'fixed_price'   => 152.00,
                'frequency'     => 'monthly',
                'is_active'     => true,
                'sort_order'    => 1,
            ],
            [
                'category_slug' => 'managed-it',
                'name'          => 'IT Managed Services - Standard Plan (5 Hrs/Month)',
                'short_name'    => 'IT Standard Plan',
                'description'   => 'Managed IT support – 5 hours of dedicated support per month.',
                'scope_items'   => [],
                'price_type'    => 'fixed',
                'fixed_price'   => 365.00,
                'frequency'     => 'monthly',
                'is_active'     => true,
                'sort_order'    => 2,
            ],
            [
                'category_slug' => 'managed-it',
                'name'          => 'IT Managed Services - Advanced Plan (10 Hrs/Month)',
                'short_name'    => 'IT Advanced Plan',
                'description'   => 'Managed IT support – 10 hours of dedicated support per month.',
                'scope_items'   => [],
                'price_type'    => 'fixed',
                'fixed_price'   => 720.00,
                'frequency'     => 'monthly',
                'is_active'     => true,
                'sort_order'    => 3,
            ],
            [
                'category_slug' => 'managed-it',
                'name'          => 'IT Managed Services - Premium Plan (20 Hrs/Month)',
                'short_name'    => 'IT Premium Plan',
                'description'   => 'Managed IT support – 20 hours of dedicated support per month.',
                'scope_items'   => [],
                'price_type'    => 'fixed',
                'fixed_price'   => 1360.00,
                'frequency'     => 'monthly',
                'is_active'     => true,
                'sort_order'    => 4,
            ],
            [
                'category_slug' => 'managed-it',
                'name'          => 'IT Managed Services - Enterprise Plan (30 Hrs/Month)',
                'short_name'    => 'IT Enterprise Plan',
                'description'   => 'Managed IT support – 30 hours of dedicated support per month.',
                'scope_items'   => [],
                'price_type'    => 'fixed',
                'fixed_price'   => 1920.00,
                'frequency'     => 'monthly',
                'is_active'     => true,
                'sort_order'    => 5,
            ],
            [
                'category_slug' => 'managed-it',
                'name'          => 'IT Managed Services - Custom Plan',
                'short_name'    => 'IT Custom Plan',
                'description'   => 'Fully flexible managed IT support – custom hours per month, priced on agreement.',
                'scope_items'   => [],
                'price_type'    => 'fixed',
                'fixed_price'   => 0.00,
                'frequency'     => 'monthly',
                'notes'         => 'Price is determined by the agreed number of hours per month.',
                'is_active'     => true,
                'sort_order'    => 6,
            ],
            [
                'category_slug' => 'managed-it',
                'name'          => 'Trend Micro Worry-Free Anti Virus',
                'short_name'    => 'Trend Micro AV',
                'description'   => 'Annual Trend Micro Worry-Free antivirus licence.',
                'scope_items'   => [],
                'price_type'    => 'fixed',
                'fixed_price'   => 72.00,
                'frequency'     => 'yearly',
                'is_active'     => true,
                'sort_order'    => 7,
            ],

            // ════════════════════════════════════════════════════════════
            //  Software & Licences  (category slug: software-licences)
            //  Note: all prices are per user per year unless stated.
            // ════════════════════════════════════════════════════════════

            // ── Microsoft 365 ──────────────────────────────────────────
            [
                'category_slug' => 'software-licences',
                'name'          => 'Microsoft 365 Business Basic',
                'short_name'    => 'M365 Business Basic',
                'price_type'    => 'fixed',
                'fixed_price'   => 108.00,
                'frequency'     => 'yearly',
                'notes'         => 'Price per user per year.',
                'is_active'     => true,
                'sort_order'    => 1,
            ],
            [
                'category_slug' => 'software-licences',
                'name'          => 'Microsoft 365 Business Standard',
                'short_name'    => 'M365 Business Standard',
                'price_type'    => 'fixed',
                'fixed_price'   => 224.40,
                'frequency'     => 'yearly',
                'notes'         => 'Price per user per year.',
                'is_active'     => true,
                'sort_order'    => 2,
            ],
            [
                'category_slug' => 'software-licences',
                'name'          => 'Microsoft 365 Business Premium',
                'short_name'    => 'M365 Business Premium',
                'price_type'    => 'fixed',
                'fixed_price'   => 394.80,
                'frequency'     => 'yearly',
                'notes'         => 'Price per user per year.',
                'is_active'     => true,
                'sort_order'    => 3,
            ],
            [
                'category_slug' => 'software-licences',
                'name'          => 'Microsoft 365 Apps for Business',
                'short_name'    => 'M365 Apps',
                'price_type'    => 'fixed',
                'fixed_price'   => 156.00,
                'frequency'     => 'yearly',
                'notes'         => 'Price per user per year.',
                'is_active'     => true,
                'sort_order'    => 4,
            ],
            [
                'category_slug' => 'software-licences',
                'name'          => 'Exchange Online (Plan 1)',
                'short_name'    => 'Exchange Online P1',
                'price_type'    => 'fixed',
                'fixed_price'   => 72.00,
                'frequency'     => 'yearly',
                'notes'         => 'Price per user per year.',
                'is_active'     => true,
                'sort_order'    => 5,
            ],
            [
                'category_slug' => 'software-licences',
                'name'          => 'Exchange Online (Plan 2)',
                'short_name'    => 'Exchange Online P2',
                'price_type'    => 'fixed',
                'fixed_price'   => 144.00,
                'frequency'     => 'yearly',
                'notes'         => 'Price per user per year.',
                'is_active'     => true,
                'sort_order'    => 6,
            ],
            [
                'category_slug' => 'software-licences',
                'name'          => 'Microsoft 365 E3 (no Teams)',
                'short_name'    => 'M365 E3',
                'price_type'    => 'fixed',
                'fixed_price'   => 639.60,
                'frequency'     => 'yearly',
                'notes'         => 'Price per user per year.',
                'is_active'     => true,
                'sort_order'    => 7,
            ],
            [
                'category_slug' => 'software-licences',
                'name'          => 'Microsoft 365 E5 (no Teams)',
                'short_name'    => 'M365 E5',
                'price_type'    => 'fixed',
                'fixed_price'   => 982.80,
                'frequency'     => 'yearly',
                'notes'         => 'Price per user per year.',
                'is_active'     => true,
                'sort_order'    => 8,
            ],
            [
                'category_slug' => 'software-licences',
                'name'          => 'Microsoft 365 F3',
                'short_name'    => 'M365 F3',
                'price_type'    => 'fixed',
                'fixed_price'   => 144.00,
                'frequency'     => 'yearly',
                'notes'         => 'Price per user per year.',
                'is_active'     => true,
                'sort_order'    => 9,
            ],
            [
                'category_slug' => 'software-licences',
                'name'          => 'Planner and Project Plan 3',
                'short_name'    => 'Project Plan 3',
                'price_type'    => 'fixed',
                'fixed_price'   => 538.80,
                'frequency'     => 'yearly',
                'notes'         => 'Price per user per year.',
                'is_active'     => true,
                'sort_order'    => 10,
            ],
            [
                'category_slug' => 'software-licences',
                'name'          => 'Planner and Project Plan 5',
                'short_name'    => 'Project Plan 5',
                'price_type'    => 'fixed',
                'fixed_price'   => 987.60,
                'frequency'     => 'yearly',
                'notes'         => 'Price per user per year.',
                'is_active'     => true,
                'sort_order'    => 11,
            ],
            [
                'category_slug' => 'software-licences',
                'name'          => 'Microsoft Teams Rooms Basic',
                'short_name'    => 'Teams Rooms Basic',
                'price_type'    => 'fixed',
                'fixed_price'   => 0.00,
                'frequency'     => 'yearly',
                'notes'         => 'Free licence per device per year.',
                'is_active'     => true,
                'sort_order'    => 12,
            ],
            [
                'category_slug' => 'software-licences',
                'name'          => 'Microsoft Teams Rooms Pro',
                'short_name'    => 'Teams Rooms Pro',
                'price_type'    => 'fixed',
                'fixed_price'   => 718.80,
                'frequency'     => 'yearly',
                'notes'         => 'Price per device per year.',
                'is_active'     => true,
                'sort_order'    => 13,
            ],
            [
                'category_slug' => 'software-licences',
                'name'          => 'Visio Plan 1',
                'short_name'    => 'Visio Plan 1',
                'price_type'    => 'fixed',
                'fixed_price'   => 90.00,
                'frequency'     => 'yearly',
                'notes'         => 'Price per user per year.',
                'is_active'     => true,
                'sort_order'    => 14,
            ],
            [
                'category_slug' => 'software-licences',
                'name'          => 'Visio Plan 2',
                'short_name'    => 'Visio Plan 2',
                'price_type'    => 'fixed',
                'fixed_price'   => 268.80,
                'frequency'     => 'yearly',
                'notes'         => 'Price per user per year.',
                'is_active'     => true,
                'sort_order'    => 15,
            ],
            [
                'category_slug' => 'software-licences',
                'name'          => 'Microsoft Intune Plan 1',
                'short_name'    => 'Intune Plan 1',
                'price_type'    => 'fixed',
                'fixed_price'   => 96.00,
                'frequency'     => 'yearly',
                'notes'         => 'Price per user per year.',
                'is_active'     => true,
                'sort_order'    => 16,
            ],
            [
                'category_slug' => 'software-licences',
                'name'          => 'Microsoft Intune Plan 2 (Add-on to Intune Plan 1)',
                'short_name'    => 'Intune Plan 2',
                'price_type'    => 'fixed',
                'fixed_price'   => 144.00,
                'frequency'     => 'yearly',
                'notes'         => 'Add-on to Intune Plan 1. Price per user per year.',
                'is_active'     => true,
                'sort_order'    => 17,
            ],
            [
                'category_slug' => 'software-licences',
                'name'          => 'Microsoft Intune Suite (Add-on to Intune Plan 1)',
                'short_name'    => 'Intune Suite',
                'price_type'    => 'fixed',
                'fixed_price'   => 216.00,
                'frequency'     => 'yearly',
                'notes'         => 'Add-on to Intune Plan 1. Price per user per year.',
                'is_active'     => true,
                'sort_order'    => 18,
            ],
            // ── Microsoft Nonprofit ────────────────────────────────────
            [
                'category_slug' => 'software-licences',
                'name'          => 'Microsoft 365 Business Standard (Nonprofit Staff Pricing)',
                'short_name'    => 'M365 Standard NFP',
                'price_type'    => 'fixed',
                'fixed_price'   => 54.00,
                'frequency'     => 'yearly',
                'notes'         => 'Nonprofit staff pricing. Price per user per year.',
                'is_active'     => true,
                'sort_order'    => 19,
            ],
            [
                'category_slug' => 'software-licences',
                'name'          => 'Microsoft 365 Business Premium (Nonprofit Staff Pricing)',
                'short_name'    => 'M365 Premium NFP',
                'price_type'    => 'fixed',
                'fixed_price'   => 98.40,
                'frequency'     => 'yearly',
                'notes'         => 'Nonprofit staff pricing. Price per user per year.',
                'is_active'     => true,
                'sort_order'    => 20,
            ],
            [
                'category_slug' => 'software-licences',
                'name'          => 'Microsoft 365 Business Basic (Nonprofit Staff Pricing)',
                'short_name'    => 'M365 Basic NFP',
                'price_type'    => 'fixed',
                'fixed_price'   => 0.00,
                'frequency'     => 'yearly',
                'notes'         => 'Nonprofit staff pricing – free. Price per user per year.',
                'is_active'     => true,
                'sort_order'    => 21,
            ],
            // ── Microsoft Education ────────────────────────────────────
            [
                'category_slug' => 'software-licences',
                'name'          => 'Microsoft 365 A5 (Education)',
                'short_name'    => 'M365 A5 Edu',
                'price_type'    => 'fixed',
                'fixed_price'   => 231.84,
                'frequency'     => 'yearly',
                'notes'         => 'Education pricing. Price per user per year.',
                'is_active'     => true,
                'sort_order'    => 22,
            ],
            [
                'category_slug' => 'software-licences',
                'name'          => 'Microsoft 365 A1 for Students',
                'short_name'    => 'M365 A1 Students',
                'price_type'    => 'fixed',
                'fixed_price'   => 0.00,
                'frequency'     => 'yearly',
                'notes'         => 'Free for students. Price per user per year.',
                'is_active'     => true,
                'sort_order'    => 23,
            ],
            [
                'category_slug' => 'software-licences',
                'name'          => 'Microsoft 365 A3 for Students',
                'short_name'    => 'M365 A3 Students',
                'price_type'    => 'fixed',
                'fixed_price'   => 62.40,
                'frequency'     => 'yearly',
                'notes'         => 'Education pricing. Price per user per year.',
                'is_active'     => true,
                'sort_order'    => 24,
            ],
            // ── Google Workspace ───────────────────────────────────────
            [
                'category_slug' => 'software-licences',
                'name'          => 'Google Workspace Business Starter',
                'short_name'    => 'GWS Starter',
                'price_type'    => 'fixed',
                'fixed_price'   => 118.80,
                'frequency'     => 'yearly',
                'notes'         => 'Price per user per year.',
                'is_active'     => true,
                'sort_order'    => 25,
            ],
            [
                'category_slug' => 'software-licences',
                'name'          => 'Google Workspace Business Standard',
                'short_name'    => 'GWS Standard',
                'price_type'    => 'fixed',
                'fixed_price'   => 237.60,
                'frequency'     => 'yearly',
                'notes'         => 'Price per user per year.',
                'is_active'     => true,
                'sort_order'    => 26,
            ],
            [
                'category_slug' => 'software-licences',
                'name'          => 'Google Workspace Business Plus',
                'short_name'    => 'GWS Plus',
                'price_type'    => 'fixed',
                'fixed_price'   => 370.80,
                'frequency'     => 'yearly',
                'notes'         => 'Price per user per year.',
                'is_active'     => true,
                'sort_order'    => 27,
            ],
            // ── Dropbox ────────────────────────────────────────────────
            [
                'category_slug' => 'software-licences',
                'name'          => 'Dropbox Personal Plus',
                'short_name'    => 'Dropbox Plus',
                'price_type'    => 'fixed',
                'fixed_price'   => 210.00,
                'frequency'     => 'yearly',
                'notes'         => 'Price per user per year.',
                'is_active'     => true,
                'sort_order'    => 28,
            ],
            [
                'category_slug' => 'software-licences',
                'name'          => 'Dropbox for Business Licence Standard',
                'short_name'    => 'Dropbox Biz Standard',
                'price_type'    => 'fixed',
                'fixed_price'   => 756.00,
                'frequency'     => 'yearly',
                'notes'         => 'Price per user per year.',
                'is_active'     => true,
                'sort_order'    => 29,
            ],
            [
                'category_slug' => 'software-licences',
                'name'          => 'Dropbox for Business Licence Advanced',
                'short_name'    => 'Dropbox Biz Advanced',
                'price_type'    => 'fixed',
                'fixed_price'   => 990.00,
                'frequency'     => 'yearly',
                'notes'         => 'Price per user per year.',
                'is_active'     => true,
                'sort_order'    => 30,
            ],
            // ── Adobe ──────────────────────────────────────────────────
            [
                'category_slug' => 'software-licences',
                'name'          => 'Adobe Acrobat Standard for Teams',
                'short_name'    => 'Acrobat Standard',
                'price_type'    => 'fixed',
                'fixed_price'   => 294.44, // source: 294.436, rounded to 2dp
                'frequency'     => 'yearly',
                'notes'         => 'Price per user per year.',
                'is_active'     => true,
                'sort_order'    => 31,
            ],
            [
                'category_slug' => 'software-licences',
                'name'          => 'Adobe Acrobat Pro for Teams',
                'short_name'    => 'Acrobat Pro',
                'price_type'    => 'fixed',
                'fixed_price'   => 414.44,
                'frequency'     => 'yearly',
                'notes'         => 'Price per user per year.',
                'is_active'     => true,
                'sort_order'    => 32,
            ],
        ];

        foreach ($products as $sortIndex => $product) {
            $categorySlug = $product['category_slug'];

            if (! isset($categoryMap[$categorySlug])) {
                $this->command->warn("Category not found for slug: {$categorySlug} – skipping product: {$product['name']}");
                continue;
            }

            $data = array_merge(
                [
                    // Defaults for optional fields
                    'short_name'        => null,
                    'description'       => null,
                    'scope_items'       => [],
                    'key_scope_keyword' => null,
                    'fixed_price'       => null,
                    'price_min'         => null,
                    'price_max'         => null,
                    'price_increment'   => null,
                    'hourly_rate'       => null,
                    'frequency'         => null,
                    'image_url'         => null,
                    'notes'             => null,
                    'is_active'         => true,
                    'sort_order'        => $sortIndex + 1,
                ],
                $product,
                ['category_id' => $categoryMap[$categorySlug]]
            );

            // Remove the helper key before persisting
            unset($data['category_slug']);

            Product::updateOrCreate(
                ['name' => $data['name']],
                $data
            );
        }
    }
}
